class AacGainLocation:
    @property
    def sample_index(self) -> int: ...
    @property
    def file_offset(self) -> int: ...
    @property
    def sample_byte_offset(self) -> int: ...
    @property
    def bit_offset(self) -> int: ...
    @property
    def channel(self) -> int: ...
    @property
    def original_gain(self) -> int: ...

class AacGainAnalysis:
    @property
    def sample_count(self) -> int: ...
    @property
    def channel_count(self) -> int: ...
    @property
    def min_gain(self) -> int: ...
    @property
    def max_gain(self) -> int: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def parse_warnings(self) -> int: ...
    @property
    def gain_locations(self) -> list[AacGainLocation]: ...

class Mp3Analysis:
    @property
    def frame_count(self) -> int: ...
    @property
    def mpeg_version(self) -> str: ...
    @property
    def channel_mode(self) -> str: ...
    @property
    def channel_count(self) -> int: ...
    @property
    def min_gain(self) -> int: ...
    @property
    def max_gain(self) -> int: ...
    @property
    def avg_gain(self) -> float: ...
    @property
    def headroom_steps(self) -> int: ...
    @property
    def headroom_db(self) -> float: ...

GAIN_STEP_DB: float

def aac_apply_gain(file_path: str, gain_steps: int) -> int: ...
def aac_apply_gain_with_undo(file_path: str, gain_steps: int) -> int: ...
def aac_undo_gain(file_path: str) -> int: ...
def aac_analyze(file_path: str) -> AacGainAnalysis: ...
def mp3_apply_gain(file_path: str, gain_steps: int) -> int: ...
def mp3_apply_gain_with_undo(file_path: str, gain_steps: int) -> int: ...
def mp3_undo_gain(file_path: str) -> int: ...
def mp3_analyze(file_path: str) -> Mp3Analysis: ...
def is_mp4_file(file_path: str) -> bool: ...
def is_aac_file(file_path: str) -> bool: ...
