class GainLocation:
    @property
    def sample_index(self) -> int: ...
    @property
    def file_offset(self) -> int: ...
    @property
    def sample_byte_offset(self) -> int: ...
    @property
    def bit_offset(self) -> int: ...
    @property
    def channel(self) -> int: ...
    @property
    def original_gain(self) -> int: ...

class GainAnalysis:
    @property
    def sample_count(self) -> int: ...
    @property
    def channel_count(self) -> int: ...
    @property
    def min_gain(self) -> int: ...
    @property
    def max_gain(self) -> int: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def parse_warnings(self) -> int: ...
    @property
    def gain_locations(self) -> list[GainLocation]: ...

GAIN_STEP_DB: float

def apply_gain(file_path: str, gain_steps: int) -> int: ...
def apply_gain_with_undo(file_path: str, gain_steps: int) -> int: ...
def undo_gain(file_path: str) -> int: ...
def analyze(file_path: str) -> GainAnalysis: ...
def is_mp4_file(file_path: str) -> bool: ...
def is_aac_file(file_path: str) -> bool: ...
